// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "arthurcadore",
            "url": "arthurcadore.github.io",
            "email": "arthurbarcella.ifsc@gmail.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/cooperativas": {
            "get": {
                "description": "Obtém a lista de todas as cooperativas",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cooperativas"
                ],
                "summary": "Lista cooperativas",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Cooperativa"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Cria uma nova cooperativa no banco de dados",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cooperativas"
                ],
                "summary": "Cria uma nova cooperativa",
                "parameters": [
                    {
                        "description": "Nova Cooperativa",
                        "name": "cooperativa",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Cooperativa"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Cooperativa"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/cooperativas/{cnpj}": {
            "delete": {
                "description": "Deleta uma cooperativa com base no CNPJ",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cooperativas"
                ],
                "summary": "Deleta uma cooperativa",
                "parameters": [
                    {
                        "type": "string",
                        "description": "CNPJ da Cooperativa",
                        "name": "cnpj",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Deletado com sucesso",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/devices": {
            "get": {
                "description": "Obtém a lista de todos os dispositivos",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "devices"
                ],
                "summary": "Lista dispositivos",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Device"
                            }
                        }
                    }
                }
            }
        },
        "/devices/{uuid}": {
            "get": {
                "description": "Obtém os dados de um dispositivo específico pelo UUID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "devices"
                ],
                "summary": "Lista dados do dispositivo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID do dispositivo",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Data"
                            }
                        }
                    }
                }
            }
        },
        "/map": {
            "get": {
                "description": "Retorna os dispositivos com as colunas UUID, LATITUDE, LONGITUDE e PESO",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "devices"
                ],
                "summary": "Lista todos os dispositivos com localização e peso",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handlers.DeviceMapResponse"
                            }
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "description": "Obtém a lista de usuários",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Lista usuários",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.User"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.DeviceMapResponse": {
            "type": "object",
            "properties": {
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                },
                "peso": {
                    "type": "number"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "models.Cooperativa": {
            "type": "object",
            "properties": {
                "cnpj": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "endereco": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                }
            }
        },
        "models.Data": {
            "type": "object",
            "properties": {
                "id_sensor": {
                    "type": "integer"
                },
                "timestamp": {
                    "type": "string"
                },
                "valor": {
                    "type": "number"
                }
            }
        },
        "models.Device": {
            "type": "object",
            "properties": {
                "altitude": {
                    "type": "number"
                },
                "firmware_version": {
                    "type": "string"
                },
                "hardware_version": {
                    "type": "string"
                },
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                },
                "peso": {
                    "type": "number"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "models.User": {
            "type": "object",
            "properties": {
                "ativo": {
                    "type": "boolean"
                },
                "email": {
                    "type": "string"
                },
                "matricula": {
                    "type": "integer"
                },
                "nome": {
                    "type": "string"
                },
                "privilegio": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "API para Sistema AgroTech",
	Description:      "Esta API permite interações com dispositivos e usuários do sistema AgroTech",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
