basePath: /api/v1
definitions:
  handlers.DeviceMapResponse:
    properties:
      latitude:
        type: number
      longitude:
        type: number
      peso:
        type: number
      uuid:
        type: string
    type: object
  models.Cooperativa:
    properties:
      cnpj:
        type: string
      email:
        type: string
      endereco:
        type: string
      nome:
        type: string
    type: object
  models.Data:
    properties:
      id_sensor:
        type: integer
      timestamp:
        type: string
      valor:
        type: number
    type: object
  models.Device:
    properties:
      altitude:
        type: number
      firmware_version:
        type: string
      hardware_version:
        type: string
      latitude:
        type: number
      longitude:
        type: number
      peso:
        type: number
      uuid:
        type: string
    type: object
  models.User:
    properties:
      ativo:
        type: boolean
      email:
        type: string
      matricula:
        type: integer
      nome:
        type: string
      privilegio:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: arthurbarcella.ifsc@gmail.com
    name: arthurcadore
    url: arthurcadore.github.io
  description: Esta API permite interações com dispositivos e usuários do sistema
    AgroTech
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: API para Sistema AgroTech
  version: "1.0"
paths:
  /cooperativas:
    get:
      description: Obtém a lista de todas as cooperativas
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Cooperativa'
            type: array
      summary: Lista cooperativas
      tags:
      - cooperativas
    post:
      consumes:
      - application/json
      description: Cria uma nova cooperativa no banco de dados
      parameters:
      - description: Nova Cooperativa
        in: body
        name: cooperativa
        required: true
        schema:
          $ref: '#/definitions/models.Cooperativa'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Cooperativa'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: Cria uma nova cooperativa
      tags:
      - cooperativas
  /cooperativas/{cnpj}:
    delete:
      consumes:
      - application/json
      description: Deleta uma cooperativa com base no CNPJ
      parameters:
      - description: CNPJ da Cooperativa
        in: path
        name: cnpj
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: Deletado com sucesso
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
      summary: Deleta uma cooperativa
      tags:
      - cooperativas
  /devices:
    get:
      description: Obtém a lista de todos os dispositivos
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Device'
            type: array
      summary: Lista dispositivos
      tags:
      - devices
  /devices/{uuid}:
    get:
      description: Obtém os dados de um dispositivo específico pelo UUID
      parameters:
      - description: UUID do dispositivo
        in: path
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Data'
            type: array
      summary: Lista dados do dispositivo
      tags:
      - devices
  /map:
    get:
      description: Retorna os dispositivos com as colunas UUID, LATITUDE, LONGITUDE
        e PESO
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handlers.DeviceMapResponse'
            type: array
      summary: Lista todos os dispositivos com localização e peso
      tags:
      - devices
  /users:
    get:
      description: Obtém a lista de usuários
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
      summary: Lista usuários
      tags:
      - users
swagger: "2.0"
