services:
  mqtt-broker:
    image: eclipse-mosquitto
    ports:
      - 1883/tcp
    restart: always
    volumes:
      - ./mqtt-broker/mosquitto.cfg:/mosquitto/config/mosquitto.conf
  database:
    environment:
      MYSQL_DATABASE: currentTS
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/secret-db
    image: mysql
    ports:
      - 3306/tcp
    restart: always
    secrets:
      - secret-db
    volumes:
      - ./database/secret-setup.sql:/docker-entrypoint-initdb.d/setup.sql
  connector:
    build:
      context: .
      dockerfile: ./connector/Dockerfile
    depends_on:
      - mqtt-broker
      - database
    restart: always
secrets:
  secret-db:
    file: ./database/secret-db
