version: '3'
services:
    mosquitto:
      build:
        context: .
        dockerfile: ./docker/Dockerfile-mqtt 
      container_name: mosquitto
      ports:
        - "1883:1883"
        # - "9001:9001"
      volumes:
        - ./config/mosquitto.cfg:/mosquitto/config/mosquitto.conf
      restart: always
    
    database:
      container_name: database
      build:
        context: .
        dockerfile: ./docker/Dockerfile-db 
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: cadore#dbmqtt

    connector:
      container_name: connector
      build:
        context: .
        dockerfile: ./docker/Dockerfile-app
      restart: always
      depends_on:
        - database
