{
 "title": "MySQL",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "UUID",
    "query": "1f3cbe5b-15dd-483e-a74a-bea00227da11,\n7f7b30cd-3a52-46b7-8615-feff437503e5,\n375311ba-6e97-4c19-8c9d-45c5c479a520,\narthur-teste"
   }
  ]
 },
 "panels": [
  {
   "title": "Probes Received",
   "type": "stat",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(ts)\r\nFROM pjiot.dados WHERE uuid='$UUID'"
    }
   ]
  },
  {
   "title": "Percentual de Probes por Device",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(ts), uuid\r\nFROM pjiot.dados GROUP BY uuid"
    }
   ]
  },
  {
   "title": "Quantidade de Probes por Device",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(ts), uuid\r\nFROM pjiot.dados GROUP BY uuid"
    }
   ]
  },
  {
   "title": "Pressão",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    {
     "rawSql": "SELECT valor, ts AS time\r\nFROM pjiot.dados WHERE uuid = '$UUID' AND idSensor = 2"
    }
   ]
  },
  {
   "title": "Temperatura",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT valor, ts AS time\r\nFROM pjiot.dados WHERE uuid = '$UUID' AND idSensor = 1"
    }
   ]
  },
  {
   "title": "Umidade",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "lumens" } },
   "targets": [
    {
     "rawSql": "SELECT valor, ts AS time\r\nFROM pjiot.dados WHERE uuid = '$UUID' AND idSensor = 4"
    }
   ]
  },
  {
   "title": "Tensão e Corrente",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "lumens" } },
   "targets": [
    {
     "rawSql": "SELECT valor, ts AS time\r\nFROM pjiot.dados WHERE uuid = '$UUID' AND idSensor = 6"
    },
    {
     "rawSql": "SELECT valor, ts AS time\r\nFROM pjiot.dados WHERE uuid = '$UUID' AND idSensor = 5"
    }
   ]
  }
 ]
}