apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: database
  name: mysql-database
  namespace: pji3
spec:
  selector:
    matchLabels:
      app: database
  replicas: 1
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootpassword
        - name: MYSQL_DATABASE
          value: example_db
        - name: MYSQL_USER
          value: example_user
        - name: MYSQL_PASSWORD
          value: password
        ports:
            - containerPort: 3306
        resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 2
              memory: 512Mi

        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d

      restartPolicy: Always

      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvc
          
      - name: init-script
        configMap:
          name: mysql-init-script
