apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: pvc
  name: mysql-database
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: database
