apiVersion: v1
kind: Service
metadata:
  labels:
    app: database
  name: mysql-database
  namespace: pji3
spec:
  type: ExternalName
  externalName: vm1.pji3.sj.ifsc.edu.br
  ports:
    - name: mqtt
      protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: mysql
