---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: database
  name: database
  namespace: pji3
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-csi
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: database
  name: database
  namespace: pji3
data:
  setup.sql: |-
    USE pjiot;
    CREATE TABLE usuario (
        matricula INT PRIMARY KEY,
        nome VARCHAR(100) NOT NULL,
        email VARCHAR(100) NOT NULL UNIQUE,
        senha VARCHAR(100) NOT NULL,
        privilegio VARCHAR(50),
        ativo BOOLEAN DEFAULT TRUE
    );
    CREATE TABLE dispositivo (
        uuid CHAR(36) PRIMARY KEY,
        hwversion VARCHAR(50),
        swversion VARCHAR(50),
        latitude DECIMAL(9, 6),
        longitude DECIMAL(9, 6),
        altitude DECIMAL(9, 2)
    );
    CREATE TABLE dispositivo_usuario (
        matricula INT,
        uuid CHAR(36),
        PRIMARY KEY (matricula, uuid),
        FOREIGN KEY (matricula) REFERENCES usuario(matricula) ON DELETE CASCADE,
        FOREIGN KEY (uuid) REFERENCES dispositivo(uuid) ON DELETE CASCADE
    );
    CREATE TABLE sensor (
        idSensor INT,
        uuid CHAR(36),
        tipo VARCHAR(50),
        unidade VARCHAR(20),
        PRIMARY KEY (idSensor, uuid),
        UNIQUE (uuid, idSensor),  -- Adicionada uma restrição UNIQUE composta para (uuid, idSensor)
        FOREIGN KEY (uuid) REFERENCES dispositivo(uuid) ON DELETE CASCADE
    );
    CREATE TABLE dados (
        ts TIMESTAMP,
        uuid CHAR(36),
        idSensor INT,
        valor DECIMAL(10, 2),
        PRIMARY KEY (ts, uuid, idSensor),
        FOREIGN KEY (uuid, idSensor) REFERENCES sensor(uuid, idSensor) ON DELETE CASCADE
    );
    CREATE USER 'connectoruser'@'%' IDENTIFIED BY 'connectorpasswrd';
    GRANT ALL PRIVILEGES ON pjiot.* TO 'connectoruser'@'%';
    FLUSH PRIVILEGES;
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: database
  name: database
  namespace: pji3
spec:
  type: ExternalName
  externalName: vm1.pji3.sj.ifsc.edu.br
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: database
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: database
  name: database
  namespace: pji3
spec:
  selector:
    matchLabels:
      app: database
  replicas: 1
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootpassword
        - name: MYSQL_DATABASE
          value: example_db
        - name: MYSQL_USER
          value: example_user
        - name: MYSQL_PASSWORD
          value: password
        ports:
          - containerPort: 3306
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 2
            memory: 512Mi
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
      restartPolicy: Always
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: database
      - name: init-script
        configMap:
          name: database
