CREATE TABLE mqttusers (
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    pw VARCHAR(255) NOT NULL,
    mosquitto_super BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE mqttacls (
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    topic VARCHAR(255) NOT NULL,
    rw INT NOT NULL DEFAULT 1
);