apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: mosquitto
    protocol: mqtt
  name: mosquitto-mosquitto-conf
  namespace: pji3
data:
  mosquitto.conf: |-
    persistence true
    persistence_location /mosquitto/data/
    autosave_interval 60
    log_dest stdout
    listener 1883
    listener 9001
    protocol websockets
    allow_anonymous true